name: Deploy to AWS ECS

on:
  push:
    branches:
        - develop
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: develop

      # Beginning of yarn setup, keep in sync between all workflows, see ci.yml
      - name: use node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: https://registry.npmjs.org/ # Needed for auth
      - name: cache all node_modules
        id: cache-modules
        uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock', '**/package.json') }}
      - name: find location of global yarn cache
        id: yarn-cache
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: cache global yarn cache
        uses: actions/cache@v4
        if: steps.cache-modules.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: yarn install
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: yarn install --immutable
      # End of yarn setup

      - name: Create Docker tags
        id: docker-tag
        run: |
          DTAG_BRANCH=$(git branch --show-current | sed 's/\//_/g')
          DTAG_SHA=$(git show -s --format=%h)
          echo "Branch:$DTAG_BRANCH, SHA:$DTAG_SHA"
          echo "DTAG_BRANCH=$DTAG_BRANCH" >> $GITHUB_OUTPUT
          echo "DTAG_SHA=$DTAG_SHA" >> $GITHUB_OUTPUT

      - name: Setup AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build api
        run: |
          cd packages/api
          yarn build

      - name: Build and tag Docker image
        run: |
          cd packages/api
          docker build \
          -t 484907489545.dkr.ecr.us-west-1.amazonaws.com/pebble-ccf:${{ steps.docker-tag.outputs.DTAG_SHA }} \
          -t 484907489545.dkr.ecr.us-west-1.amazonaws.com/pebble-ccf:${{ steps.docker-tag.outputs.DTAG_BRANCH }} \
          -t 484907489545.dkr.ecr.us-west-1.amazonaws.com/pebble-ccf:latest .

      - name: Push Docker images to ECR
        run: |
          cd packages/api
          docker push 484907489545.dkr.ecr.us-west-1.amazonaws.com/pebble-ccf:${{ steps.docker-tag.outputs.DTAG_SHA }}
          docker push 484907489545.dkr.ecr.us-west-1.amazonaws.com/pebble-ccf:${{ steps.docker-tag.outputs.DTAG_BRANCH }}
          docker push 484907489545.dkr.ecr.us-west-1.amazonaws.com/pebble-ccf:latest

      - name: Render ECS task definition
        id: render-pebble-ccf
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: deploy.json
          container-name: pebble-ccf
          image: 484907489545.dkr.ecr.us-west-1.amazonaws.com/pebble-ccf:${{ steps.docker-tag.outputs.DTAG_SHA }}

      - name: DocumentDB
        with: 
          aws-auth-mode: ${{ secrets.AWS_AUTH_MODE }}
          aws-target-account-role-name: ${{ secrets.AWS_TARGET_ACCOUNT_ROLE_NAME }}
          documentdb-uri: ${{ secrets.DOCUMENTDB_URI }}
          documentdb-ssl-ca-file: ${{ secrets.DOCUMENTDB_SSL_CA_FILE }}
          documentdb-username: ${{ secrets.DOCUMENTDB_USERNAME }}
          documentdb-password: ${{ secrets.DOCUMENTDB_PASSWORD }}
          cache-mode: ${{ secrets.CACHE_MODE }}
          tenant-db: ${{ secrets.TENANT_DB }}

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.render-pebble-ccf.outputs.task-definition }}
          cluster: pebble-dev-cluster
          service: pebble-ccf
          force-new-deployment: true
          enable-ecs-managed-tags: true
